### ISSUE TITLE
Sega Mapping Guide Issue

### ISSUE THREAD

**Issue by rtomasa** [mdqinc/SDL_GameControllerDB#817]
Hi,

I noticed that the mapping guide for Sega Saturn like controllers uses a weird placement for LB/RB and LT/RT.
L/R should be LT/RT and Z/C should be LB/RB.
Beyond this being a more logical placement, there are games/frontends/emulators that provide remapping only for the same type of buttons. For example, you can only assigns trigger to another trigger but not mix buttons and triggers.
I would suggest something like this:
![mapping_guide](https://github.com/user-attachments/assets/d18b2202-e62a-45e4-af49-7fb182f32790)

**Comment by offalynne** [comment]
Hi @rtomasa, I see your perspective on this and am sympathetic; the layout is a bit problematic. However SDL follows the [Hori format](https://www.google.com/search?q=hori+fighting+controller&tbs=imgo:1&udm=2) for Arcade and Saturn mappings. Since we are downstream of SDL, this decision is not ours to make, or change.

> *"games/frontends/emulators that provide remapping only for the same type of buttons"*

I understand this data is being used by code projects independently of SDL, but that is not the database's intended use. All of the assumptions regarding data format match the SDL project.

If you want to take the issue upstream to [SDL](https://github.com/libsdl-org/SDL), if they make the change we will follow, but I doubt that will be the case.

I'm sympathetic that this may be an issue for ReplayOS; if you would like help in identifying Saturn pads in the db so you can flip the mappings in your copy of the db (or handle it internally in your software), feel free to let me know and I'll help as best I can.

**Comment by rtomasa** [comment]
ohhh my gosh, Hori mappings, so Xbox internally and Hori as physical layout. This one I had no idea.
OK I totally understand that you cannot go against SDL standard, so I will try to identify those gamepads using similar layout with the help of my community and create a parallel DB with those. Not sure if you are interested on having those mappings too. Let me know and I will try to provide you some update from time to time.

Thanks for the info

**Comment by offalynne** [comment]
> *"Not sure if you are interested on having those mappings too"*

Please, yes !

**Comment by offalynne** [comment]
> *"I will try to identify those gamepads"*

In another project (MIT license) I have correlated gamepad type with VID+PID: https://github.com/offalynne/Input/blob/community-data/community_gamepad_type.txt#L105-L143

That project combines the community data and the following SDL data: https://github.com/libsdl-org/SDL/blob/main/src/joystick/controller_list.h

...to build a final list of gamepad types here: https://github.com/offalynne/Input/blob/master/datafiles/controllertypes.csv

`CommunitySaturn` should help you identify pads with Saturn form factor.

**Comment by offalynne** [comment]
Different issue but potentially of interest; you can also use the above data to identify Nintendo style BAYX layout from the following types:

`SwitchHandheld`, `SwitchJoyConPair`, `SwitchProController`, `XInputSwitchController`, `SwitchInputOnlyController`, `CommunityLikeSwitch`, `Community8BitDo`, `HIDWiiClassic`, `CommunitySNES`, `CommunitySuperFamicom`

**Comment by rtomasa** [comment]
Many thanks. I will look into this info and come back once I have something useful to share.
